### ISSUE TITLE
There should be an automated uninstaller for easy uninstallation of st2 and its deps. 

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2workroom#270]
Requested by @blach on slack.

**Comment by manasdk** [comment]
I guess our base assumption was that a VM is cheap to create and destroy. I guess this is not true?

**Comment by Kami** [comment]
Yes, that should still be our assumption, imo.

Right now, creating a complete uninstaller is basically impossible since it would also mess with system dependencies (Python libraries, Ruby libraries, etc.). On top of that, users should also dedicate server to StackStorm, otherwise they will encounter dependency hell themselves.

In the future, when things are more contained, we can at least make it easier to uninstall st2 services and related Python dependencies.
