### ISSUE TITLE
No response from stackstorm when executing ansible command from Slack

### ISSUE THREAD

**Issue by Tibingeo** [StackStorm/st2workroom#342]
I am getting  no response from stackstorm when executing ansible command from Slack 
Stackstrom error log is in this link http://pastebin.com/xxEqn04W

**Comment by Kami** [comment]
Which version of StackStorm are you running (`st2 --version`)?

There was a bug in ChatOps in v1.3.0.11 which has been fixed in 1.3.0.12. If you are indeed using an old and affected version, please see "Important Notes" section in this article (http://stackstorm.reamaze.com/kb/installation/upgrade-from-v1-dot-2-to-v1-dot-3) for information on how to upgrade to the latest release where the bug has been fixed.

**Comment by Tibingeo** [comment]
Action is getting executed in st2 , when I run "ansible uname" command in slack it tells 'Let me get right on that. Remember xxxx' and then nothing happens

**Comment by Kami** [comment]
@Tibingeo This indeed sounds like bug which was fixed in the latest v1.3.0-12 release.

Please see my comment above (notably which version you are running) and the linked knowledge base article.
